# Site
repository: eax94/eax94.github.io
favicon: images/favicon.ico

# Personal info
name: Lucas García Laporta
title: Senior Software Engineer
email: lucas.garcia.laporta@gmail.com
address: London, United Kingdom
address_google_maps: https://www.google.com/maps/@51.5048029,-0.1519304,12.25z

# Dark Mode
darkmode: true

# Social links
#twitter_username:
github_username: EAX94
stackoverflow_username: "4671900"
#hackerrank_username: "KISKE"
#dribbble_username:
#facebook_username:
#flickr_username:
#instagram_username:
linkedin_username: lucas-garcía-laporta
#xing_username:
#pinterest_username:
#youtube_username:
#googleplus_username:
#orcid_username:

#
# Use | for a new line
#

# About Section
about_title: About Me
#about_profile_image: images/profile.png
about_content: As a Senior Software Engineer, I bring over a decade of experience in game development, with a focus on optimization, performance tuning, and system enhancements. My work involves implementing robust gameplay features, identifying and resolving performance bottlenecks, and improving engine systems to ensure seamless user experiences.

# Experience Section
experience_title: Experience

# Education Section
education_title: Education

# Projects Section
projects_title: Projects

# More Section
#more_title: Interests
#more_content: |
#  + Reverse engineering.
#  + Artificial intelligence.
#  + Chess.
#  + Astronomy.

# Footer
footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
